apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app-manager
  template:
    metadata:
      labels:
        app: hr-app-manager
    spec:
      containers:
      - name: hr-app-manager
        image: saketh1809/cap-app-management:v1.1.0
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://rootuser:rootpassword@localhost:27017/hr_system?authSource=rootuser"
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: hr-app-manager-service
spec:
  selector:
    app: hr-app-manager
  ports:
  - port: 3001
    targetPort: 3000
  type: LoadBalancer